### PR TITLE
Fixed PR Template issue (makes it auto gen when people make a PR)

### LINKED ISSUE #124: [Bug]: (PR Template, not auto displaying when someone creates a Pull Request)
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

Pull request template doesn't auto generate when someone creates pull request, unlike this repo https://github.com/mjkahan/github_demo_repo/blob/main/.github/pull_request_template.md

### Release version

Current

### Steps to reproduce

1.  Create a pull request

### What platform are you seeing this problem on?

_No response_

### Relevant log output

```shell
none
```

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Fixes #124 + Updated PR Template

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@ThioJoe Please merge this to fix the problem.

**Comment by KendallDoesCoding** [comment]
Fixed #124

**Comment by KendallDoesCoding** [comment]
Fixes #124

**Comment by KendallDoesCoding** [comment]
@ThioJoe, I tried to follow this to auto-assign you to the pull request 
https://egghead.io/lessons/github-auto-assign-a-pull-request-on-github

Although, it didnt seem to work.

**Review by KendallDoesCoding — COMMENTED** [review]
@TechStudent11 you added this in your code to auto assign @ThioJoe to the issue, will this work for PR too?

assignees:
  - ThioJoe

**Comment by TechStudent11** [comment]
@KendallDoesCoding 
Edit the description of the PR to say:
```
Fixes #124 + Updated PR Template
```

**Comment by TechStudent11** [comment]
@KendallDoesCoding DESCRIPTION NOT TITLE

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding DESCRIPTION NOT TITLE

Sorry lol

**Comment by TechStudent11** [comment]
It's fine

**Comment by KendallDoesCoding** [comment]
Thanks a lot @ThioJoe

**Comment by KendallDoesCoding** [comment]
It works now...

**Pull request merged**
