### PR TITLE
Move main code into `main()`

### PR DESCRIPTION
**Pull request by TechStudent11**
It is proper convention to put all the code that is running at execution in a function called `main`. Then using `if __name__ == "__main__"` to run it.

### CODE REVIEW

**Comment by ThioJoe** [comment]
Doesn't run

**Comment by TechStudent11** [comment]
@ThioJoe After refactoring, the code does run. However, it does have issues deleting comments made by me. Is that a normal thing or no? What I had to do was find all the variables that had issues, go back to the top of the file and add a new line that gave the variable a default value. Would this be the reason? You could check my fork to see.

Btw, here is the output:
```
============ YOUTUBE SPAMMER PURGE v1.4.0-Testing ============
== https://github.com/ThioJoe/YouTube-Spammer-Purge ==
======== Author: ThioJoe - YouTube.com/ThioJoe =======

Purpose: Lets you scan and mass delete all comments from a specific user at once

NOTE: It's probably better to scan a single video, because you can scan all those comments,
      but scanning your entire channel must be limited and might miss older spam comments.
You WILL be shown the comments to confirm before they are deleted.

    >  Currently logged in user: TechStudent10 (Channel ID: UCzb9_b2UY29xuY-S8BsmpOg )

       Continue as this user? (y/n): y

-----------------------------------------------------------------
~~ Do you want to scan a single video, or your entire channel? ~~
      1. Scan Single Video
      2. Scan Entire Channel
Choice: 1
Enter Video link or ID to scan: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol
Chosen Video:  test

Is this correct? (y/n): y
Enter the Channel link(s) or ID(s) of the spammer (comma separated): UCzb9_b2UY29xuY-S8BsmpOg


WARNING: You are scanning for your own channel ID! This would delete all of your comments on the video!
     (You WILL still be asked to confirm before actually deleting anything)
If you are testing and want to scan and/or delete your own comments, enter 'Y' to continue, otherwise enter 'N' to exit.

Continue? (y/n): y
Scanning...

Top Level Comments Scanned: 12 | Replies Scanned: 0 | Spam Found So Far: 12

Number of Spammer Comments Found: 12

Spam comments ready to display. Also save the list to a text file? (y/n): y
Log file will be called Spam_Log_2021-11-07_11-22-36.txt

Press Enter to display comments...


Comments by the selected user:

1. TechStudent10:  This video is to test ThioJoe's YouTube Spammer Purge. So spam all you want, but it will get deleted.
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=Ugz0l7DxxQq-jx5IXrl4AaABAg

2. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgwZ5eQT6Fa5k85xXaF4AaABAg

3. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgycS3ylT6l9E1TJUdx4AaABAg

4. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgwfC22li7fY-P7U5-V4AaABAg

5. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgzFSLzWMkJm-iSorcR4AaABAg

6. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=Ugz-UfsHXlm5gC6OfA54AaABAg

7. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=Ugzi-aycjO_cV8M0cJ94AaABAg

8. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgzelxGMQa3K2W8c0bh4AaABAg

9. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgzLGna_ID-u6KRYYS14AaABAg

10. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgzHzqsZ8ADiwGdmSbx4AaABAg

11. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=Ugwq2x2UgcgCdsFAomx4AaABAg

12. TechStudent10:  this is spam
     > Direct Link: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgwUSGrOPj5a5dFDRtR4AaABAg



Check that all comments listed above are indeed spam.
Do you want to delete ALL of the above comments? Type 'YES' exactly, in all caps!
YES

Also ban the spammer(s) ? (y/n): n


Deleting Comments. Please Wait...
Comments Deleted! Will now verify each is gone.

Possible Issue Deleting Comment: Ugz0l7DxxQq-jx5IXrl4AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=Ugz0l7DxxQq-jx5IXrl4AaABAg
Possible Issue Deleting Comment: UgwZ5eQT6Fa5k85xXaF4AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgwZ5eQT6Fa5k85xXaF4AaABAg
Possible Issue Deleting Comment: UgycS3ylT6l9E1TJUdx4AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgycS3ylT6l9E1TJUdx4AaABAg
Possible Issue Deleting Comment: UgwfC22li7fY-P7U5-V4AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgwfC22li7fY-P7U5-V4AaABAg
Possible Issue Deleting Comment: UgzFSLzWMkJm-iSorcR4AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgzFSLzWMkJm-iSorcR4AaABAg
Possible Issue Deleting Comment: Ugz-UfsHXlm5gC6OfA54AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=Ugz-UfsHXlm5gC6OfA54AaABAg
Possible Issue Deleting Comment: Ugzi-aycjO_cV8M0cJ94AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=Ugzi-aycjO_cV8M0cJ94AaABAg
Possible Issue Deleting Comment: UgzelxGMQa3K2W8c0bh4AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgzelxGMQa3K2W8c0bh4AaABAg
Possible Issue Deleting Comment: UgzLGna_ID-u6KRYYS14AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgzLGna_ID-u6KRYYS14AaABAg
Possible Issue Deleting Comment: UgzHzqsZ8ADiwGdmSbx4AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgzHzqsZ8ADiwGdmSbx4AaABAg
Possible Issue Deleting Comment: Ugwq2x2UgcgCdsFAomx4AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=Ugwq2x2UgcgCdsFAomx4AaABAg
Possible Issue Deleting Comment: UgwUSGrOPj5a5dFDRtR4AaABAg |  Check Here: https://www.youtube.com/watch?v=ThisIsMyTestVideoIdNotReallyLol&lc=UgwUSGrOPj5a5dFDRtR4AaABAg


Warning: 12 spam comments may remain. Check links above or try running the program again.

Deletion Complete. Press Enter to Exit...

Finished Executing.
```

**Comment by ThioJoe** [comment]
Yea based on what I was reading, as it stands now the code has the "main" variables declared at the 'top level' so they can be read by anywhere, but if they want to be changed they would need to be set as global inside a function. But if everything gets moved into a main function, they become local variables and need to be either declared outside main or set as global in every function that uses them. I might be able to adjust it myself by adding an extra commit to the pull request.

Also have you checked if the comments were indeed still there? Using the API you can actually get info about comments even without the video ID, so I checked a few and they returned nothing, so perhaps the warning was erroneous? Or perhaps they are on a private video? Not sure if that would make a difference.

**Comment by TechStudent11** [comment]
@ThioJoe I used this on a test, unlisted video. I actually checked YouTube Studio and apparently, YouTube wants me to approve the spam comments. I don't think I set the video to hold all comments for review, but after I approve of them I'll check if it (the script) still works. Also, I will allow edits by maintainers, if that allows you to add commits.

**Comment by TechStudent11** [comment]
So I think I glitched YouTube. I can check YouTube (on the same account I spammed on) and the comments are there. BUT if I check YouTube Studio, it says that there are 0 comments on the video. Then if I check the comments, there are a bunch of comments with an approve button, but they do absolutely nothing. And to top it all of, if I check the "Held for review" tab on the same video, there is nothing. Definitely glitched.

**Pull request merged**
