### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code
- Not phrased properly
- Added a comment 

## Type of change

Please delete options that are not relevant.

- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Proposed Changes
- Added a comment 
- Phrased a little better.

### CODE REVIEW

**Comment by ThioJoe** [comment]
It's fine

**Comment by RDKRACZ** [comment]
@KendallDoesCoding if you want to do grammar corrections then you better learn proper grammar first.

**Comment by KendallDoesCoding** [comment]
> It's fine

Yeah.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding if you want to do grammar corrections then you better learn proper grammar first.

What was wrong @RDKRACZ ??

**Comment by RDKRACZ** [comment]
Indefinite article, here
> but a updated

**Comment by KendallDoesCoding** [comment]
Ik, it should be but an updated version is coming soon, right?

**Comment by KendallDoesCoding** [comment]
I forgot the n lol, but I knew that.

**Pull request closed without merging**
