### PR TITLE
Update pull_request_template.md

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code
- Like the issue template has, I am working on a way that we could auto assign @ThioJoe as a assignee

## Type of change
- [ ] New feature (non-breaking change which adds functionality)

# Proposed Changes
- Auto assignee ThioJoe, when someone creates a pull request

# Additional Info
@TechStudent11 , you did this for the issue template, I would need your help for this too.

## Checklist:

- [ ] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [(Not yet done because this is a draft)] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

# Screenshots

Original | Updated
:----------------------:|:-----------:
** original screenshot  | ** updated screenshot **

### CODE REVIEW

**Comment by TechStudent11** [comment]
I'm already working on this.

**Comment by KendallDoesCoding** [comment]
> I'm already working on this.

So, should I close this PR?

**Comment by TechStudent11** [comment]
@KendallDoesCoding Sure.

**Comment by KendallDoesCoding** [comment]
Closing in favour of #120

**Pull request closed without merging**
