### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by MalikIdreesHasanKhan**
Typos in the YoutubeSpammerPurge.py have been fixed.

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
approved

**Comment by MalikIdreesHasanKhan** [comment]
@KendallDoesCoding Thank You!

**Review by TechStudent11 — APPROVED** [review]
I didn't even notice those! Approved.

**Comment by MalikIdreesHasanKhan** [comment]
Thank You @ThioJoe

**Pull request merged**
