### PR TITLE
Partly finished pull request form

### PR DESCRIPTION
**Pull request by TechStudent11**

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@TechStudent11 what happened to #109?

**Comment by TechStudent11** [comment]
Got merged

**Comment by TechStudent11** [comment]
huh

**Comment by TechStudent11** [comment]
I didn't get the template

**Comment by TechStudent11** [comment]
Something must've gotten messed up.

**Comment by KendallDoesCoding** [comment]
> Something must've gotten messed up.

Yeah even my template has gotten messed up?

**Comment by KendallDoesCoding** [comment]
@TechStudent11 Just a heads up, the same thing will happen here as I mentioned in #121 as Github updated.

It doesn't auto add it to the pull request. I think github had some updates.

**Comment by KendallDoesCoding** [comment]
@ThioJoe , @TechStudent11 Actually, I'm still not sure if you can add a template auto or not.

This video is from April and it worked just fine

URL: https://youtu.be/MjsS4ujX3nU

**Comment by KendallDoesCoding** [comment]
> I didn't get the template

I got it!

**Comment by KendallDoesCoding** [comment]
> > Something must've gotten messed up.
> 
> Yeah even my template has gotten messed up?

I fixed it now in #125

**Comment by KendallDoesCoding** [comment]
> _No description provided._

Please make the description as follows:

Fixes #149

**Comment by ThioJoe** [comment]
I'm a bit confused about the purpose of this, being a draft. Is it still being worked on? Or was the template added via another pull request?

**Comment by KendallDoesCoding** [comment]
> I'm a bit confused about the purpose of this, being a draft. Is it still being worked on? Or was the template added via another pull request?

This is partly finished I believe, what we want to do is basically auto assign you to the pull request and make the template much neater then it currently is .yaml files make templated better formatted and stuff. @TechStudent11 is working on this, so that's why for now it's a draft @ThioJoe .

**Comment by TechStudent11** [comment]
@ThioJoe I think I'm gonna stop working on this. The PR template is fine as is.

cc. @KendallDoesCoding

**Comment by KendallDoesCoding** [comment]
> @ThioJoe I think I'm gonna stop working on this. The PR template is fine as is.
> 
> cc. @KendallDoesCoding

Ok cool! I thought it would look neater, but that's a lot of hard work and extra code going into it so yeah lol.

**Pull request closed without merging**
