### PR TITLE
Update bug_report.yaml

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Add another field for the duplicate issues

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
It's done, but I just need @TechStudent11 to set it so that if one of the two boxes are selected, you can submit the issue, without having the check both the boxes.

**Review by TechStudent11 — APPROVED** [review]
the second one shouldn't be required.

**Comment by TechStudent11** [comment]
oops, meant to request changes

**Comment by KendallDoesCoding** [comment]
> the second one shouldn't be required.

Done.

**Comment by KendallDoesCoding** [comment]
Pog! It works well now.

**Pull request merged**
