### PR TITLE
Use click for arch linux and command line users.

### PR DESCRIPTION
**Pull request by MXP2095onetechguy**
Before, it uses print, not click.echo_with_pager() with the help of [click](https://click.palletsprojects.com/en/8.0.x/). 

That may be fine for Ubuntu, windows or desktop users, but for arch and command line users, not really(If they don't have a desktop). This pager will help them read through everything without the text zooming to quickly.

### CODE REVIEW

**Comment by flexagoon** [comment]
I don't think that some people use their computer entirely without X11/Wayland/etc, just in a tty. Changing the script just so that people who do that can scroll back is useless. People who use a TTY are either masochists or working on a server. In either case, it's their fault that they can't scroll back to read what the app outputs.

**Comment by flexagoon** [comment]
Wait, the original script was logging stuff into a file anyways. Then there's no point at all in using click. If errors are logged into a file, even console-only users can open it in a text editor like Nano or Vim and scroll back to see the outputs.

**Comment by flexagoon** [comment]
This PR is weird. Instead of WRITING something to a log file, you suggest READING from an empty log file and then printing that into a console with click??

**Comment by ThioJoe** [comment]
Yea these edits make no sense

**Pull request closed without merging**
