### PR TITLE
update issue form so that platform is required

### PR DESCRIPTION
**Pull request by TechStudent11**
also added clarification that Linux can also be Replit

# Related Issue/Addition to code
- None

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Proposed Changes
- update issue form so that platform is required
- made clarification that Linux can also be Replit

## Checklist:

- [ ] My code follows the style guidelines of this project and have read CONTRIBUTING.md
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by KendallDoesCoding — COMMENTED** [review]
It doesn't work on Replit and @ThioJoe, isn't comfortable with sharing the client_secrets.json file with third party websites.

**Comment by TechStudent11** [comment]
@KendallDoesCoding Got it.

**Comment by KendallDoesCoding** [comment]
pog, thanks

**Review by KendallDoesCoding — APPROVED** [review]
approved

**Pull request merged**
