### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
A code of conduct is suggested by github.

### CODE REVIEW

**Review by TechStudent11 — APPROVED** [review]
Agreed. This should be here.

**Comment by KendallDoesCoding** [comment]
> Agreed. This should be here.

Thanks!

**Review by KendallDoesCoding — COMMENTED** [review]
@TechStudent11 , @ThioJoe I added ThioJoe & Community, but you guys can make it just ThioJoe

**Comment by ThioJoe** [comment]
Eh this isn't really necessary and the default template covers way too much stuff that doesn't apply. This is a small project so I'll just be removing anything off topic anyway.

**Comment by KendallDoesCoding** [comment]
> Eh this isn't really necessary and the default template covers way too much stuff that doesn't apply. This is a small project so I'll just be removing anything off topic anyway.

Ok! Just thought it would be useful cause github suggests it!

**Pull request closed without merging**
