### PR TITLE
update script with BIG letters for title

### PR DESCRIPTION
**Pull request by TechStudent11**
Just an aesthetics change.

### CODE REVIEW

**Review by KendallDoesCoding — APPROVED** [review]
This isn't necessary though.

**Comment by TechStudent11** [comment]
> Just an aesthetics change.

@KendallDoesCoding I said it's **just** an aesthetics change. The code doesn't have to be merged.

**Comment by ThioJoe** [comment]
Eh it's not really necessary and would take up more space when someone opens the window. Plus it's another non standard module that would have to be included.

**Comment by TechStudent11** [comment]
@ThioJoe yeah I guess you're right.

**Pull request closed without merging**
