### PR TITLE
Solution for Unsupported Devices / Android Users to be able to run code

### LINKED ISSUE #110: on my linux device it says the file type is not suported even though it's for linux

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Updates pull request from #117 

Many people are complaining, that they cannot run the code on Linux and that they cannot run the program at all on Android (which is obvious why for Android), so I added a way for Android users to run this program too, and Linux users to run this program too and edit the code too.

I think Linux is a major concern if .exe doesn't run on the OS and if the code had different variations between Windows and Linux.

@ThioJoe , if you want, you can add another txt file with my instructions instead of it being in the README.md

Fixes #110

### CODE REVIEW

**Review by KendallDoesCoding — COMMENTED** [review]
As per @ThioJoe;s comment on #116 , I think instead of calling:
pip install rtfunicode
pip install colorama
pip install google-api-python-client

We just need to call upon the requirements.txt file, although for now as I have tested this I'm leaving it as it is, but if we can cut out these 3 lines of code and replace it with one line, that would be good, but I just need to complete my testing on this.

**Comment by KendallDoesCoding** [comment]
> As per @ThioJoe's comment on #116 , I think instead of calling: pip install rtfunicode pip install colorama pip install google-api-python-client
> 
> We just need to call upon the requirements.txt file, although for now as I have tested this I'm leaving it as it is, but if we can cut out these 3 lines of code and replace it with one line, that would be good, but I just need to complete my testing on this.

@ThioJoe I just tested it and it works, please request changes for updating this!

**Comment by KendallDoesCoding** [comment]
> > As per @ThioJoe's comment on #116 , I think instead of calling: pip install rtfunicode pip install colorama pip install google-api-python-client
> > We just need to call upon the requirements.txt file, although for now as I have tested this I'm leaving it as it is, but if we can cut out these 3 lines of code and replace it with one line, that would be good, but I just need to complete my testing on this.
> 
> @ThioJoe I just tested it and it works, please request changes for updating this!

I figured out how to commit without you having to request changes. Please merge Removed 3 pips, made it into 1 to main.

**Comment by TechStudent11** [comment]
@KendallDoesCoding maybe edit the description to say:

```
Updates pull request from #117 

Many people are complaining, that they cannot run the code on Linux and that they cannot run the program at all on Android (which is obvious why for Android), so I added a way for Android users to run this program too, and Linux users to run this program too and edit the code too.

I think Linux is a major concern if .exe doesn't run on the OS and if the code had different variations between Windows and Linux.

@ThioJoe , if you want, you can add another txt file with my instructions instead of it being in the README.md

Fixes #110 
```

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding maybe edit the description to say:
> 
> ```
> Updates pull request from #117 
> 
> Many people are complaining, that they cannot run the code on Linux and that they cannot run the program at all on Android (which is obvious why for Android), so I added a way for Android users to run this program too, and Linux users to run this program too and edit the code too.
> 
> I think Linux is a major concern if .exe doesn't run on the OS and if the code had different variations between Windows and Linux.
> 
> @ThioJoe , if you want, you can add another txt file with my instructions instead of it being in the README.md
> 
> Fixes #110 
> ```

Thanks.

**Review by TechStudent11 — CHANGES_REQUESTED** [review]
`<p>pip install -r requirements.txt</p>` should just be:

```markdown
```bash
pip install -r requirements.txt
```
With an ending of ```.

**Comment by KendallDoesCoding** [comment]
> `<p>pip install -r requirements.txt</p>` should just be:
> 
> ```gfm
> ```bash
> pip install -r requirements.txt
> ```
> 
> With an ending of ```.

Well, it worked with what I put, Should I update it to pip install -r requirements.txt```

What does the ``` stand for @TechStudent11 ?

**Comment by KendallDoesCoding** [comment]
Oh ok, first lemme test it, if it works, I'll edit it. You can create a
pull request in my forked version of the repo
https://github.com/KendallDoesCoding/YouTube-Spammer-Purge

In branch, patch 3

**Review by KendallDoesCoding — COMMENTED** [review]
@ThioJoe If you want, you can get rid of the pip install -r requirements.txt line, and edit it to be, follow installation mentioned above

above = above on README.md

**Comment by KendallDoesCoding** [comment]
> `<p>pip install -r requirements.txt</p>` should just be:
> 
> ```gfm
> ```bash
> pip install -r requirements.txt
> ```
> 
> With an ending of ```.

With this, Idk if its working or not, but it doesn't print out if its installing or no.

**Comment by KendallDoesCoding** [comment]
@ThioJoe Waiting for your reply... What do you think on this?

**Comment by KendallDoesCoding** [comment]
@ThioJoe Can you please review this, put the comment in the wrong PR.

**Comment by ThioJoe** [comment]
I'll have to look into this, I try to minimize recommending third party services when possible. Also need to make sure it works with the GUI portion

**Comment by KendallDoesCoding** [comment]
Yeah, I don't like using third party services too, but to make everything
much easier for Linux and possibly Android users, I think this is a good
option. Ofc, feel free to review this!

**Comment by KendallDoesCoding** [comment]
Because, rn we are getting lots of complaints from Linux users, who don't
understand how to set it up.

**Comment by KendallDoesCoding** [comment]
I can do a screen recording to show how it works for you @ThioJoe.

**Comment by ThioJoe** [comment]
Frankly if someone is using linux they should be able to figure out how to install python

**Comment by KendallDoesCoding** [comment]
Yes, but as we can see from the issues, that's not the case. I think people
these days, just download Linux, without knowing how to use it lol

**Comment by KendallDoesCoding** [comment]
#110, #106, #59, #65, #54, are some of them.

**Comment by KendallDoesCoding** [comment]
> @ThioJoe I'm getting a error, but I just think it's a code error, I'm creating a issue thread.

#136, Please fix this so I can test out how the code runs on replit.com

**Comment by KendallDoesCoding** [comment]
@TechStudent11 , @ThioJoe Nay, I don't think this would work actually.

Got this error on replit.

   Loading...

Log in using the browser window.

^CTraceback (most recent call last):
  File "YouTubeSpammerPurge.py", line 2289, in <module>
    main()
  File "YouTubeSpammerPurge.py", line 1720, in main
    youtube = get_authenticated_service() # Set easier name for API function
  File "YouTubeSpammerPurge.py", line 126, in get_authenticated_service
    creds = flow.run_local_server(port=0, authorization_prompt_message="Log in using the browser window.")
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 472, in run_local_server
    local_server.handle_request()
  File "/usr/lib/python3.8/socketserver.py", line 294, in handle_request
    ready = selector.select(timeout)
  File "/usr/lib/python3.8/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt

**Comment by KendallDoesCoding** [comment]
> @TechStudent11 , @ThioJoe Nay, I don't think this would work actually.
> 
> Got this error on replit.
> 
> Loading...
> 
> Log in using the browser window.
> 
> ^CTraceback (most recent call last): File "YouTubeSpammerPurge.py", line 2289, in main() File "YouTubeSpammerPurge.py", line 1720, in main youtube = get_authenticated_service() # Set easier name for API function File "YouTubeSpammerPurge.py", line 126, in get_authenticated_service creds = flow.run_local_server(port=0, authorization_prompt_message="Log in using the browser window.") File "/opt/virtualenvs/python3/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 472, in run_local_server local_server.handle_request() File "/usr/lib/python3.8/socketserver.py", line 294, in handle_request ready = selector.select(timeout) File "/usr/lib/python3.8/selectors.py", line 415, in select fd_event_list = self._selector.poll(timeout) KeyboardInterrupt

@TechStudent11 Tell me if you know how to sort this out, otherwise I will close this PR.

**Comment by KendallDoesCoding** [comment]
I'm trying it out again, I have a weird glitch with my chrome!

**Comment by KendallDoesCoding** [comment]
@TechStudent11 , @ThioJoe Nay, doesn't work

https://replit.com/join/bhxcmqnbjn-kendalldoescodi

**Comment by KendallDoesCoding** [comment]
But, I didnt see anything in the window that opened too, which said login
to the window.

**Comment by TechStudent11** [comment]
> But, I didnt see anything in the window that opened too, which said login to the window.

@KendallDoesCoding ? Anyways, I'm going to bed now. It's about 10 PM. Actually, it's to 11.

**Comment by KendallDoesCoding** [comment]
No problem, yeah 10 and a half hours difference, It will be 11 in 5 minutes.

**Comment by ThioJoe** [comment]
I don't think I want to officially support a method that requires people to upload or store their authentication credentials on a third party site

**Comment by TechStudent11** [comment]
I guess you're right, yeah.

**Comment by KendallDoesCoding** [comment]
> I don't think I want to officially support a method that requires people to upload or store their authentication credentials on a third party site

Yup, I get what you mean. I didn't think of that until you said this. Also, it anyway doesn't seem to be working so I'm closing this ticket. I just thought it would be a good idea, because we are getting lots of reports saying its not running for Linux.

**Comment by KendallDoesCoding** [comment]
@ThioJoe I think the online version of VS Code would work, I don't think of it as a third party service, because if I couldn't run .exe files, I would just run it in VS Code, although, I can't figure out how to run python there. 

@TechStudent11 , @ThioJoe Let me know if you can figure out how to, the url for the vscode online is here - https://vscode.dev/github/ThioJoe/YouTube-Spammer-Purge

It should have the github repo already opened, it worked for me.

**Comment by KendallDoesCoding** [comment]
I changed the README.md to this for the time-being, obviously it wont stay like this if we figure out how we can run the code in vs code's online website.

**Comment by TechStudent11** [comment]
You can't. [vscode.dev](https://vscode.dev) can't run terminals. If you want to do that, you need a Codespace, which costs money.

**Comment by KendallDoesCoding** [comment]
Isn't Github Codespaces free?

**Comment by TechStudent11** [comment]
@KendallDoesCoding Not it isn't. [github.dev](https://github.dev) might be what you're thinking about. That's the online GitHub editor. [Codespaces](https://github.com/codespaces) on the other hand, makes you pay for VMs to write your code on.

**Comment by KendallDoesCoding** [comment]
Got it!

**Comment by KendallDoesCoding** [comment]
@ThioJoe Do you know any IDE software that let's you run code online?

**Comment by KendallDoesCoding** [comment]
It seems like no...

Closing this PR, again!

**Comment by KendallDoesCoding** [comment]
> Uhhh....android users can just use termux, a linux terminal emulator that can run and install actual linux software... so if it works in linux, it should work in termux
> 
> https://termux.com/

Oh wow, interesting. I would mention this to the README file. But, idk how it works and @ThioJoe mentioned he doesn't like inculding third party services. So yeah. But good to know!

**Comment by KendallDoesCoding** [comment]
Actually, let me delete branch.

**Pull request closed without merging**
