### PR TITLE
Create user-friendly issue template (issue form)

### LINKED ISSUE #105: Add issue (and PR) templates with user-friendly fields.
I've seen GitHub experiment with Issue and Pull Request templates. It's actually very cool! What happens is instead of copying and pasting the template Markdown file, if you use a `.yml` (Yaml) file, it gives you actual fields! This is apparent in the [`electron/electron`](https://github.com/electron/electron) repository.

_Electron Issue Template_

image

I feel like this would be more user-friendly because @ThioJoe is targeting creators and most creators have probably never worked with Markdown on GitHub.

_Originally posted by @TechStudent11 in https://github.com/ThioJoe/YouTube-Spammer-Purge/pull/104#pullrequestreview-822031848_

### PR DESCRIPTION
**Pull request by TechStudent11**
Fixes #105

### CODE REVIEW

**Comment by TechStudent11** [comment]
Here's what it looks like:

image

**Comment by TechStudent11** [comment]
New updated version (with duplicate issue(s) box):

image

**Comment by TechStudent11** [comment]
Here's what it looks like now (I had to decrease my browser window to 80%)

image

**Comment by ThioJoe** [comment]
Ok i'll definitely merge this one when i get around to it

**Comment by TechStudent11** [comment]
@ThioJoe okay!

**Comment by TechStudent11** [comment]
@ThioJoe AYYYYYYYYYYYYYYYYYYY!

**Comment by TechStudent11** [comment]
I tested it in #119 

cc @ThioJoe

**Comment by KendallDoesCoding** [comment]
@ThioJoe I think the same thing applies, as I mentioned in #121 here too, as Github had a update... Its a shame, really

For reference: 
@ThioJoe, it doesn't auto add it to the pull request. I think github had some updates.

**Comment by KendallDoesCoding** [comment]
@ThioJoe , @TechStudent11 Actually, I'm still not sure if you can add a template auto or not.

This video is from April and it worked just fine

URL: https://youtu.be/MjsS4ujX3nU

**Comment by KendallDoesCoding** [comment]
Hey, You can auto add it, check out this repo and see if you can figure out what they added that we didnt @TechStudent11 - https://github.com/mjkahan/github_demo_repo/blob/main/.github/pull_request_template.md

cc: @ThioJoe

**Comment by KendallDoesCoding** [comment]
Actually, for this it auto gens it, only for my PR's it doesnt work @TechStudent11 , Ignore the above messeges, Sorry!

**Pull request merged**
