### PR TITLE
Update pull_request_template.md

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Updation of pull request template

It didnt seem to work before.

### CODE REVIEW

**Comment by KendallDoesCoding** [comment]
@TechStudent11 can you help me with testing if it works or no? I can see the template but it doesn't auto gen when I create a PR

**Comment by KendallDoesCoding** [comment]
@TechStudent11 , @ThioJoe, Template issue #122

**Comment by TechStudent11** [comment]
@KendallDoesCoding I gotta go. I'll be back soon.

**Comment by KendallDoesCoding** [comment]
K. cya

**Comment by KendallDoesCoding** [comment]
@ThioJoe, it doesn't auto add it to the pull request. I think github had some updates.

**Comment by KendallDoesCoding** [comment]
cc @TechStudent11

**Comment by KendallDoesCoding** [comment]
@ThioJoe although, please merge this in as it's a better version of the template.

**Comment by KendallDoesCoding** [comment]
@ThioJoe , @TechStudent11 Actually, I'm still not sure if you can add a template auto or not.

This video is from April and it worked just fine

URL: https://youtu.be/MjsS4ujX3nU

**Comment by KendallDoesCoding** [comment]
Hey, You can auto add it, check out this repo and see if you can figure out what they added that we didnt @TechStudent11 - https://github.com/mjkahan/github_demo_repo/blob/main/.github/pull_request_template.md

cc: @ThioJoe

**Comment by KendallDoesCoding** [comment]
@ThioJoe Figured out issue why it doesnt auto gen

**Comment by KendallDoesCoding** [comment]
Fixed all the issues + updated template at #125

**Pull request closed without merging**
