### PR TITLE
web-browser

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
# Related Issue/Addition to code

- Open github links mentioned in the code in web browser when tapped. Right now, users can only see the link and not click and view it.

### CODE REVIEW

**Comment by ThioJoe** [comment]
This might not work with the windows console, not sure

**Comment by KendallDoesCoding** [comment]
> This might not work with the windows console, not sure

I think it should work with the module, but the bad part is that it will just open it in the browser. Idk if it can be set to open on click or after a certain while in time. If you don't like this, then I'll be happy to close it :)

**Comment by ThioJoe** [comment]
Yea if it just opens up a browser window automatically, definitely not want that

**Comment by KendallDoesCoding** [comment]
> Yea if it just opens up a browser window automatically, definitely not want that

Yeah, I'll keep this open though for a while and see if I can figure out any way to make it so that if the user taps, it opens, if your fine with that :)

**Comment by KendallDoesCoding** [comment]
Actually, I'll close it now and reopen if I find a way to do this.

**Comment by KendallDoesCoding** [comment]
@ThioJoe How does the google authenticate link open in the browser automatically though in the .exe atleast. Means, there is a way to get this done?

**Comment by Dobby233Liu** [comment]
> @\ThioJoe How does the google authenticate link open in the browser automatically though in the .exe atleast. Means, there is a way to get this done?

https://github.com/ThioJoe/YT-Spammer-Purge/blob/main/Scripts/auth.py#L74 -> https://github.com/googleapis/google-auth-library-python-oauthlib/blob/main/google_auth_oauthlib/flow.py#L468

**Comment by Firecul** [comment]
You could add to the script "Do you wish to go to this website just now?" sort of thing @KendallDoesCoding?

**Comment by KendallDoesCoding** [comment]
> You could add to the script "Do you wish to go to this website just now?" sort of thing @KendallDoesCoding?

I'm not too a good at Python, but I'll try doing it.

**Pull request closed without merging**
