### PR TITLE
More than one scammer scanned at once

### PR DESCRIPTION
**Pull request by joaogelado**
I'm making this pull request to comapability to scan more than one scammer

### CODE REVIEW

**Comment by joaogelado** [comment]
Please, just give me a moment to repair the conflicts and arrange some stuff

**Comment by joaogelado** [comment]
Also... can anyone tell me why is conflitted?

**Comment by ThioJoe** [comment]
I gotta be honest i have no idea what is going on in this one lol, theres so many changes and commits

**Comment by joaogelado** [comment]
> I gotta be honest i have no idea what is going on in this one lol, theres so many changes and commits

In reality, these commits are me trying to fix the conflicts...

**Comment by joaogelado** [comment]
If you don't understand, you can close this pull request, don't worry. I will try to make it more trivial next pull requests

**Comment by joaogelado** [comment]
I will close it because many stuff can be confused and the firsts commits are old, some commits before version 1.3.3

**Pull request closed without merging**
