### PR TITLE
Added the ability to instead of choosing max amount of scanned comments, you can choose the max amount of time of scanning comments

### PR DESCRIPTION
**Pull request by FrostDevGithub**
Hi ThioJoe or however is reading this (massive fan btw)
With this build, I have added the ability to choose a max amount of time of scanning (in minutes or seconds) instead of max amount of comments
I currently don't have the project done (basically I haven't connected the google API yet) (so it says: ERROR: client_secrets.json file not found!). so I can't test this, but it's separate and the changes have been directly tested and worked!
Please have a look at this
Cheers!

### CODE REVIEW

**Review by TechStudent11 — CHANGES_REQUESTED** [review]
Very nice! I would just ask if you could change how the user chooses between scanning for amount of comments and time of scanning for comments. Maybe something like "Or, press enter to choose a max time for scanning for comments" and then check if `maxScanNumber` equals nothing. If so, ask the user for the maximum amount of time to scan for comments.

Also, `str.startsWith()` exists. So instead of writing:

```python
if TMP_scantime[0] == 'M':
```

You could write:

```python
if TMP_scantime.startsWith('M'):
```

Other than that, looks good!

**Comment by FrostDevGithub** [comment]
Thanks for the suggestion @TechStudent11 
I will add al of them!
Sadly enough I can’t access my pc right now
But hopefully the changes will be out by tonight
Please keep in mind that without these changes everything is still functional
Do merging or at least approving would be highly appreciated

**Comment by TechStudent11** [comment]
@FrostDevGithub I don't have write access so I can't merge this. I am a contributor, meaning I have committed code to this repo. If I was a collaborator, I could merge this. Anyways, if you want to push code to this repo, you need to commit it to the `patch-1` branch. GitHub should tell you which branch to push to, but as this is your first PR, you should commit to `patch-1`.

**Comment by ThioJoe** [comment]
I appreciate the work put into this. Though I'm not sure this is something I'd want to implement tbh. Because the amount of replies hugely affects the speed of the scanning, a timer-based scan would lead to wildly inconsistent numbers of comments scanned depending on the video. (The API basically makes a call to get 50 top level comments, and looks at which ones has at least one reply, then has to do an individual separate call for each thread with replies to get the replies. So theoretically if every single thread had >1 replies, it would take 50x as long as a video where no comments had replies.)

I've been more thinking of just adding a way for the user to be able to stop scanning at any time.

**Comment by FrostDevGithub** [comment]
Hi! afcourse the abilty to stop scanning at any time would fix a big part of the problem which i was really annoyed by (not being able to just leave it running in the night, and stop it when i get back)
But until then i think this feature could still be pretty usefull
I see where youre coming from ofcourse
And i understand that this would be very inconsistant, but even then i still think some users might find this feature usefull
If you dont want to add this to main branch i understand, but maybe adding it to a branch with experimental features would be a good idea?
idk i just think that not implementing this in any way would kinda be a waste

**Comment by FrostDevGithub** [comment]
@TechStudent11 i have made the changes you requested
Cheers

**Comment by KendallDoesCoding** [comment]
> I appreciate the work put into this. Though I'm not sure this is something I'd want to implement tbh. Because the amount of replies hugely affects the speed of the scanning, a timer-based scan would lead to wildly inconsistent numbers of comments scanned depending on the video. (Because of the way the API resources work, the script basically has to make a call to get 50 top level comments as a group, and then looks at which ones has at least one reply, then has to do an individual separate API call for each thread with replies to get those replies. So theoretically if every single thread had >1 replies, it would take 50x as long as a video where no comments had replies.)
> 
> I've been more thinking of just adding a way for the user to be able to stop scanning at any time.

Yeah, I personally think like the concept of @FrostDevGithub's idea, but what your saying is true. A feature, to allow the user to stop scanning at any point at time would really be good/useful and would love to see it come in the future to the program...

**Review by KendallDoesCoding — COMMENTED** [review]
What is this supposed to do?

**Comment by KendallDoesCoding** [comment]
> Hi! afcourse the abilty to stop scanning at any time would fix a big part of the problem which i was really annoyed by (not being able to just leave it running in the night, and stop it when i get back) But until then i think this feature could still be pretty usefull I see where youre coming from ofcourse And i understand that this would be very inconsistant, but even then i still think some users might find this feature usefull If you dont want to add this to main branch i understand, but maybe adding it to a branch with experimental features would be a good idea? idk i just think that not implementing this in any way would kinda be a waste

I think its a good idea, but the API should be able to handle it at the same time, right?

**Comment by KendallDoesCoding** [comment]
@ThioJoe , @TechStudent11 Kindly close this pull request, due to the reasons stated above by ThioJoe himself.

Have a great day!
Kendall Does Coding

**Comment by FrostDevGithub** [comment]
@KendallDoesCoding uhm no. 
ThioJoe himself said that there are problems with this but the idea is good. 
The problem is outside of my “reach” as its a problem with the api not my code
And the problem isn’t even that big, it’s just inconsistency 

If ThioJoe wanted to close this he would have but he didn’t as this feature is still “in progress”
As the only problem is inconsistency  and multiple people agree that that’s not enough to close this

We have multiple options (of which @ThioJoe himself can do what he wants):
He can close this for the reasons he stated
He can keep this open until further developments to the api fix the issues, and then I or someone else can update this to include the new updates
He can implement this right now and just add a label that this feature is still in beta
Or he can add this to a separate branch with experimental features

Kindly wait for ThioJoe to make a decision 
Have a great day

**Comment by TechStudent11** [comment]
@KendallDoesCoding @FrostDevGithub I am NOT a collaborator. I would love to, but I'm not sure if @ThioJoe would agree. So I can't just close this nor merge this. Anyways, I agree with @FrostDevGithub. This feature is still in progress so until it's done, it should remain open.

P.S: @ThioJoe I would say yes if you asked me if I wanted to be a collaborator.

**Comment by TechStudent11** [comment]
P.S it says I'm a contributer. That just means I've had one or more pull requests merged. I think I have about 3.

**Comment by KendallDoesCoding** [comment]
> @KendallDoesCoding uhm no. ThioJoe himself said that there are problems with this but the idea is good. The problem is outside of my “reach” as its a problem with the api not my code And the problem isn’t even that big, it’s just inconsistency
> 
> If ThioJoe wanted to close this he would have but he didn’t as this feature is still “in progress” As the only problem is inconsistency and multiple people (including @ThioJoe and @TechStudent11) agree that that’s not enough to close this
> 
> We have multiple options (of which @ThioJoe himself can do what he wants): He can close this for the reasons he stated He can keep this open until further developments to the api fix the issues, and then I or someone else can update this to include the new updates He can implement this right now and just add a label that this feature is still in beta Or he can add this to a separate branch with experimental features
> 
> Kindly wait for ThioJoe to make a decision Have a great day

Even, I like the concept, just was wondering why this pull request was still open and inactive after so many days, let @ThioJoe make a decision on this though!

**Comment by KendallDoesCoding** [comment]
@ThioJoe - Please get back on this...

**Comment by TechStudent11** [comment]
It's been a week...

**Comment by KendallDoesCoding** [comment]
> It's been a week...

Yes, it has been 13 days since @ThioJoe commented on this, and 7 days since this thread has been active...

**Comment by ThioJoe** [comment]
Yea this was one is gonna be a nah from me, but thanks. If there's demand for it at some point i could reopen it

**Comment by KendallDoesCoding** [comment]
> Yea this was one is gonna be a nah from me, but thanks. If there's demand for it at some point i could reopen it

👍

**Pull request closed without merging**
