### PR TITLE
Add logs for reporting bugs.

### PR DESCRIPTION
**Pull request by TechStudent11**
This gives users the link to report bugs after pressing enter to exit.

### CODE REVIEW

**Review by osadavc — APPROVED** [review]

**Comment by ThioJoe** [comment]
I'll probably merge this, though the message would have to go before the input() line otherwise the window will just close too quickly for them to see it.

**Comment by TechStudent11** [comment]
@ThioJoe yeah I didn't think of that. I change it then you can merge.

**Comment by TechStudent11** [comment]
@ThioJoe Changed. You should be able to merge now.

**Comment by TechStudent11** [comment]
There were some merge conflicts that I think I solved.

**Pull request merged**
