### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
It is suggested by github to set a Pull request template, Idk if this would work, yall may have to do some settings inside the pull request, if you guys decide to merge this.

This feature is suggested by github, because it helps make the project pull requests, more user friendly.

### CODE REVIEW

**Review by TechStudent11 — COMMENTED** [review]
I've seen GitHub experiment with Issue and Pull Request templates. It's actually very cool! What happens is instead of copying and pasting the template Markdown file, if you use a `.yml` (Yaml) file, it gives you actual fields! This is apparent in the [`electron/electron`](https://github.com/electron/electron) repository.

_Electron Issue Template_

image

I feel like this would be more user-friendly because @ThioJoe is targeting creators and most creators have probably never worked with Markdown on GitHub.

**Comment by KendallDoesCoding** [comment]
> I've seen GitHub experiment with Issue and Pull Request templates. It's actually very cool! What happens is instead of copying and pasting the template Markdown file, if you use a `.yml` (Yaml) file, it gives you actual fields! This is apparent in the [`electron/electron`](https://github.com/electron/electron) repository.
> 
> _Electron Issue Template_
> 
> image
> 
> I feel like this would be more user-friendly because @ThioJoe is targeting creators and most creators have probably never worked with Markdown on GitHub.

I don't really understand what you mean by this....

**Comment by TechStudent11** [comment]
@KendallDoesCoding I'm saying that there is now a new, more user-friendly way to create issues and pull requests.

**Comment by KendallDoesCoding** [comment]
Oh ok, Then lets go ahead doing it , if possible cause Github suggests
stuff like this.

**Comment by TechStudent11** [comment]
@KendallDoesCoding There should be some documentation on how to do this. You can check it out.

**Comment by KendallDoesCoding** [comment]
Ok, I will check it out. Thanks!

**Comment by TechStudent11** [comment]
No prob :)

**Comment by KendallDoesCoding** [comment]
@TechStudent11 , should I close this issue, considering you already made another pull request, with a better idea then this?

**Comment by TechStudent11** [comment]
@TechStudent11 Well, sure if you want. But I created an issue form. Not a PR form. So I don't think you should close this.

**Comment by KendallDoesCoding** [comment]
Ok, I'll leave it open for now!

**Comment by ThioJoe** [comment]
I'll also merge this i think i havent had a chance to really look at it

**Comment by KendallDoesCoding** [comment]
> I'll also merge this i think i havent had a chance to really look at it

Ok cool!

**Comment by KendallDoesCoding** [comment]
@ThioJoe thanks!

**Comment by KendallDoesCoding** [comment]
@TechStudent11 my template doesn't seem to work though?

**Comment by TechStudent11** [comment]
wait

**Comment by TechStudent11** [comment]
You're right

**Comment by KendallDoesCoding** [comment]
Yeah, I thought it would work, but it doesn't. Can you figure out the error?

**Comment by TechStudent11** [comment]
Maybe

**Pull request merged**
