### PR TITLE
Make video ID checking more generic

### PR DESCRIPTION
**Pull request by ryanolee**
# What
This PR aims to expand the video ID detection 

# How
By redefining the logic to extract an ID with a regular expression based on https://regexr.com/3dj5t which should be able to extract the video ID in more cases / with more consistency. 

# Why
In order to get fewer false negatives when A user enters a link containing a valid video ID. This should hopefully cover nearly all cases where a link might contain a video ID

# Caveats 
This PR contains a fairly convoluted regular expression which may reduce overall maintainability as outlined in the `CONTRIBUTING.md`. So it is still open for debate as to if this change is worth merging.

# To test:
The function can be seen as new verses old here: https://ideone.com/hGXOhM

```bash
Testing for video ID: 'https://www.youtube.com/watch?v=DFYRQ_zQ-gk&feature=featured' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'https://www.youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'http://www.youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: '//www.youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'www.youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'https://youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'http://youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: '//youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'https://m.youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'http://m.youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: '//m.youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'm.youtube.com/watch?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'https://www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US' New: (True, 'DFYRQ_zQ-gk') Old: (False, None)
Testing for video ID: 'http://www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US' New: (True, 'DFYRQ_zQ-gk') Old: (False, None)
Testing for video ID: '//www.youtube.com/v/DFYRQ_zQ-gk?fs=1&hl=en_US' New: (True, 'DFYRQ_zQ-gk') Old: (False, None)
') Old: (False, None)
Testing for video ID: 'youtube.com/embed/DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (False, None)
Testing for video ID: 'https://youtu.be/DFYRQ_zQ-gk?t=120' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'https://youtu.be/DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'http://youtu.be/DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: '//youtu.be/DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
Testing for video ID: 'youtu.be/DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (False, None)
Testing for video ID: 'https://www.youtube.com/HamdiKickProduction?v=DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (False, None)
Testing for video ID: 'NotAValidLinksdfsdfsdf' New: (False, None) Old: (False, None)
Testing for video ID: 'DFYRQ_zQ-gk' New: (True, 'DFYRQ_zQ-gk') Old: (True, 'DFYRQ_zQ-gk')
```

### CODE REVIEW

**Comment by ThioJoe** [comment]
Hm ok I'll look over this when I get the chance, Regex would be the ideal method

**Comment by seraphya** [comment]
The regex doesn't take into account localizations, but maybe it doesn't need to.
see link for examples:
https://stackoverflow.com/a/65375894

**Comment by ryanolee** [comment]
Ah I see what you mean 🤔

**Comment by ThioJoe** [comment]
I merged this PR but looks like your email address used to push the commits was different than your GitHub account, so it's not showing you in the contributors list. I think if you add the other one to your account it should show up, or I can add you as a co-author to the most recent commit so at least you'll show up as a contributor if you want.

**Comment by ryanolee** [comment]
Ahh I don't particularly mind! Feel to add me as a co-author if you want too see if that works but don't mind if I don't appear in the contributors. Just wanted to make the tool a bit better 🚀

**Pull request merged**
